# Generated by Django 4.0.6 on 2022-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Description')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
